pluginManagement {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
    plugins {
        id("com.android.application") version "8.11.1"
        id("com.android.library") version "8.11.1"
        id("dev.rikka.tools.refine") version "4.4.0"
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
    versionCatalogs {
        libs {
            version("hidden-api", "4.4.0")
            library("hidden-compat", "dev.rikka.hidden", "compat").versionRef("hidden-api")
            library("hidden-stub", "dev.rikka.hidden", "stub").versionRef("hidden-api")

            version("refine", "4.4.0")
            library("refine-runtime", "dev.rikka.tools.refine", "runtime").versionRef("refine")
        }
    }
}

rootProject.name = "porter-api"
include ":aidl", ":shared", ":api", ":provider", ":shizuku-compat", ":protocol", ":sdk"

def includeExtras = providers.gradleProperty("includeExtras").getOrElse("false").toBoolean()
def includeShell = providers.gradleProperty("includeShell").getOrElse("false").toBoolean()

if (includeExtras || includeShell) {
    include ":porsh", ":server-shared"
}

if (includeExtras) {
    include ":demo", ":demo-hidden-api-stub"
}
